resolver: lts-6.9
packages:
- '.'
- location:
    git: https://github.com/morishin/hsmecab.git
    commit: 2da6677fbd42bb77d3b6e61c02edfeebe248e184
- location:
    git: https://github.com/aiya000/hs-twi-high.git
    commit: 0fb25ead1af4738e47b5fd159cb94bbf0fd69665
- location: './hs-sentence-jp'
extra-deps: []
flags: {}
extra-package-dbs: []
extra-include-dirs: [/app/.linuxbrew/include]
extra-lib-dirs: [/app/.linuxbrew/lib]
