resolver: lts-9.2
packages:
- '.'
- location: './hsmecab'
- location: './hs-twi-high'
- location: './hs-sentence-jp'
extra-deps: []
flags: {}
extra-package-dbs: []
extra-include-dirs: [/app/.linuxbrew/include]
extra-lib-dirs: [/app/.linuxbrew/lib]
